require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Restaurant = require('../src/models/Restaurant');

const RESTAURANTS = [
  // ── CRESCENT MALL ─────────────────────────────────────────────────────────
  {
    name: 'The Pizza Company',
    category: 'Pizza & Mì Ý', cuisine: 'Ý',
    address: 'Tầng 3, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['pizza', 'pasta', 'ý', 'crescent mall'],
    description: 'Chuỗi pizza lớn với nhiều topping, dành cho gia đình và nhóm bạn.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'Gong Cha',
    category: 'Trà & Đồ uống', cuisine: 'Hàn Quốc',
    address: 'Tầng G, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['trà sữa', 'bubble tea', 'hàn quốc', 'crescent mall'],
    description: 'Trà sữa Đài Loan nổi tiếng, topping đa dạng, ít ngọt tuỳ chỉnh.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'Burger King',
    category: 'Burger & Fast Food', cuisine: 'Mỹ',
    address: 'Tầng G, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['burger', 'fast food', 'gà rán', 'crescent mall'],
    description: 'Chuỗi burger Mỹ với Whopper, gà giòn, và khoai tây chiên.',
    open_hours: '09:00–22:00',
  },
  {
    name: 'Lotteria',
    category: 'Burger & Fast Food', cuisine: 'Hàn Quốc',
    address: 'Tầng G, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['burger', 'gà rán', 'hàn quốc', 'fast food', 'crescent mall'],
    description: 'Lotteria nổi tiếng với burger tôm và gà giòn kiểu Hàn.',
    open_hours: '09:00–22:00',
  },
  {
    name: 'Baskin-Robbins',
    category: 'Kem & Tráng miệng', cuisine: 'Mỹ',
    address: 'Tầng G, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$$', tags: ['kem', 'tráng miệng', 'crescent mall'],
    description: '31 vị kem nổi tiếng, có bánh kem theo yêu cầu.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'Tous Les Jours',
    category: 'Bánh & Cà phê', cuisine: 'Hàn Quốc',
    address: 'Tầng G, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['bánh mì', 'tiệm bánh', 'cà phê', 'hàn quốc', 'crescent mall'],
    description: 'Tiệm bánh Hàn Quốc với bánh kem, bánh ngọt và cà phê.',
    open_hours: '08:00–22:00',
  },
  {
    name: 'Highlands Coffee',
    category: 'Cà phê', cuisine: 'Việt Nam',
    address: 'Tầng G, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['cà phê', 'trà', 'việt nam', 'crescent mall'],
    description: 'Chuỗi cà phê Việt với cà phê phin, freeze và bánh snack.',
    open_hours: '07:00–22:00',
  },
  {
    name: "McDonald's Crescent Mall",
    category: 'Burger & Fast Food', cuisine: 'Mỹ',
    address: 'Tầng G, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['burger', 'mcflurry', 'gà rán', 'fast food', 'crescent mall'],
    description: 'McDonald\'s với Big Mac, McNugget, McFlurry và breakfast.',
    open_hours: '07:00–23:00',
  },
  {
    name: 'Popeyes',
    category: 'Gà rán & Fast Food', cuisine: 'Mỹ',
    address: 'Tầng G, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['gà rán', 'louisiana', 'fast food', 'crescent mall'],
    description: 'Gà rán kiểu Louisiana nổi tiếng với vỏ giòn đặc trưng.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'Starbucks Crescent Mall',
    category: 'Cà phê', cuisine: 'Mỹ',
    address: 'Tầng G, Crescent Mall, 101 Tôn Dật Tiên, P. Tân Phú',
    ward: 'Tân Phú', area: 'Crescent Mall',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$$$', tags: ['cà phê', 'frappuccino', 'cold brew', 'crescent mall'],
    description: 'Starbucks với Frappuccino, cold brew và pastry nhập khẩu.',
    open_hours: '07:00–22:30',
  },

  // ── SC VIVOCITY ────────────────────────────────────────────────────────────
  {
    name: 'KFC SC VivoCity',
    category: 'Gà rán & Fast Food', cuisine: 'Mỹ',
    address: 'Tầng 1, SC VivoCity, 1058 Nguyễn Văn Linh, P. Tân Phong',
    ward: 'Tân Phong', area: 'SC VivoCity',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['gà rán', 'kfc', 'fast food', 'vivocity'],
    description: 'KFC gà rán giòn kiểu Kentucky, combo bucket gia đình.',
    open_hours: '09:00–22:00',
  },
  {
    name: 'Jollibee SC VivoCity',
    category: 'Burger & Fast Food', cuisine: 'Philippines',
    address: 'Tầng 1, SC VivoCity, 1058 Nguyễn Văn Linh, P. Tân Phong',
    ward: 'Tân Phong', area: 'SC VivoCity',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['burger', 'spaghetti', 'gà', 'fast food', 'vivocity'],
    description: 'Jollibee với Chickenjoy, Jolly Spaghetti và hamburger đặc trưng.',
    open_hours: '09:00–22:00',
  },
  {
    name: 'Pizza Hut SC VivoCity',
    category: 'Pizza & Mì Ý', cuisine: 'Mỹ',
    address: 'Tầng 3, SC VivoCity, 1058 Nguyễn Văn Linh, P. Tân Phong',
    ward: 'Tân Phong', area: 'SC VivoCity',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['pizza', 'pasta', 'vivocity'],
    description: 'Pizza Hut với stuffed crust, pan pizza và khu ăn uống rộng rãi.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'Phúc Long SC VivoCity',
    category: 'Trà & Đồ uống', cuisine: 'Việt Nam',
    address: 'Tầng G, SC VivoCity, 1058 Nguyễn Văn Linh, P. Tân Phong',
    ward: 'Tân Phong', area: 'SC VivoCity',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['trà sữa', 'trà xanh', 'việt nam', 'vivocity'],
    description: 'Phúc Long nổi tiếng với trà sữa trứng và trà xanh truyền thống.',
    open_hours: '08:00–22:00',
  },
  {
    name: 'The Coffee House SC VivoCity',
    category: 'Cà phê', cuisine: 'Việt Nam',
    address: 'Tầng G, SC VivoCity, 1058 Nguyễn Văn Linh, P. Tân Phong',
    ward: 'Tân Phong', area: 'SC VivoCity',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['cà phê', 'việt nam', 'vivocity'],
    description: 'The Coffee House với cà phê sữa đá, bánh mì và không gian làm việc.',
    open_hours: '07:00–22:30',
  },
  {
    name: 'Bonchon SC VivoCity',
    category: 'Gà rán', cuisine: 'Hàn Quốc',
    address: 'Tầng 3, SC VivoCity, 1058 Nguyễn Văn Linh, P. Tân Phong',
    ward: 'Tân Phong', area: 'SC VivoCity',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['gà rán', 'hàn quốc', 'sốt ngọt cay', 'vivocity'],
    description: 'Gà rán Hàn Quốc Bonchon với sốt ganjang và yangnyeom đặc trưng.',
    open_hours: '10:00–22:00',
  },

  // ── PHÚ MỸ HƯNG & NGUYỄN VĂN LINH ────────────────────────────────────────
  {
    name: 'Phở Hùng Phú Mỹ Hưng',
    category: 'Phở & Bún', cuisine: 'Việt Nam',
    address: '18 Nguyễn Thị Thập, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['phở', 'bún bò', 'việt nam', 'phú mỹ hưng'],
    description: 'Phở bò và phở gà truyền thống, nước dùng đậm đà ngọt xương.',
    open_hours: '06:00–22:00',
  },
  {
    name: 'Cơm Tấm Thuận Kiều',
    category: 'Cơm tấm', cuisine: 'Việt Nam',
    address: '36 Huỳnh Tấn Phát, P. Tân Thuận Tây',
    ward: 'Tân Thuận Tây', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['cơm tấm', 'sườn bì chả', 'việt nam'],
    description: 'Cơm tấm sườn bì chả, trứng ốp la, mỡ hành thơm.',
    open_hours: '06:00–21:00',
  },
  {
    name: 'Cháo Sườn Bắc Kim',
    category: 'Cháo & Xôi', cuisine: 'Việt Nam',
    address: '88 Nguyễn Thị Thập, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$', tags: ['cháo', 'sườn', 'việt nam'],
    description: 'Cháo sườn non, cháo gà và xôi mặn ăn sáng.',
    open_hours: '06:00–11:00',
  },
  {
    name: 'Bún Bò Huế Mợ Tám',
    category: 'Phở & Bún', cuisine: 'Việt Nam',
    address: '120 Lê Văn Lương, P. Tân Hưng',
    ward: 'Tân Hưng', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['bún bò huế', 'bún', 'việt nam', 'cay'],
    description: 'Bún bò Huế cay đặc trưng với chả cua và giò heo.',
    open_hours: '06:30–21:00',
  },
  {
    name: 'Cơm Nhà Phú Mỹ Hưng',
    category: 'Cơm văn phòng', cuisine: 'Việt Nam',
    address: '15 Phan Văn Trị, P. Phú Mỹ',
    ward: 'Phú Mỹ', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['cơm bình dân', 'cơm văn phòng', 'việt nam'],
    description: 'Cơm bình dân nhiều món, xuất văn phòng, giao nhanh.',
    open_hours: '10:00–20:00',
  },
  {
    name: 'Bún Đậu Mắm Tôm Phú Mỹ Hưng',
    category: 'Bún đậu', cuisine: 'Việt Nam',
    address: '22 Nguyễn Thị Thập, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['bún đậu', 'mắm tôm', 'việt nam'],
    description: 'Bún đậu mắm tôm chuẩn vị Hà Nội, đủ bộ nem, chả cốm.',
    open_hours: '10:00–21:00',
  },
  {
    name: 'Bánh Mì Huỳnh Hoa',
    category: 'Bánh mì', cuisine: 'Việt Nam',
    address: '26 Lê Thị Riêng (chi nhánh), P. Tân Thuận Tây',
    ward: 'Tân Thuận Tây',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['bánh mì', 'việt nam', 'đặc sản'],
    description: 'Bánh mì nhân thịt nguội, pate, dưa leo nổi tiếng Sài Gòn.',
    open_hours: '15:00–23:00',
  },
  {
    name: 'Dim Sum House Phú Mỹ Hưng',
    category: 'Dimsum & Trung Hoa', cuisine: 'Trung Hoa',
    address: '10A Nguyễn Văn Linh, P. Tân Phong',
    ward: 'Tân Phong', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['dimsum', 'há cảo', 'sủi cảo', 'trung hoa'],
    description: 'Dimsum sáng và trưa với há cảo, sủi cảo hấp, xíu mại.',
    open_hours: '07:00–14:00',
  },
  {
    name: 'Buffet Lẩu Phú Mỹ Hưng',
    category: 'Lẩu & Nướng', cuisine: 'Việt Nam',
    address: '56 Nguyễn Thị Thập, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: false, shopee_food: false, be_food: false },
    price_range: '$$', tags: ['lẩu', 'buffet', 'nhóm', 'việt nam'],
    description: 'Lẩu buffet đủ loại: lẩu Thái, lẩu nấm, lẩu hải sản.',
    open_hours: '10:00–22:00',
  },

  // ── LOTTE MART QUẬN 7 ─────────────────────────────────────────────────────
  {
    name: 'Foodcourt Lotte Mart Q7',
    category: 'Food Court', cuisine: 'Đa dạng',
    address: 'Tầng 4, Lotte Mart, 469 Nguyễn Hữu Thọ, P. Tân Hưng',
    ward: 'Tân Hưng', area: 'Lotte Mart Q7',
    platforms: { grab: false, shopee_food: false, be_food: false },
    price_range: '$', tags: ['food court', 'đa dạng', 'gia đình'],
    description: 'Khu ẩm thực đa dạng trong siêu thị Lotte Mart Q7.',
    open_hours: '09:00–22:00',
  },
  {
    name: 'Caffe Bene Lotte Mart Q7',
    category: 'Cà phê', cuisine: 'Hàn Quốc',
    address: 'Tầng G, Lotte Mart, 469 Nguyễn Hữu Thọ, P. Tân Hưng',
    ward: 'Tân Hưng', area: 'Lotte Mart Q7',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$$', tags: ['cà phê', 'waffle', 'hàn quốc', 'lotte mart'],
    description: 'Caffe Bene với waffle Bỉ, red velvet cake và cà phê Hàn.',
    open_hours: '09:00–22:00',
  },

  // ── ĐƯỜNG NGUYỄN HỮU THỌ ──────────────────────────────────────────────────
  {
    name: 'Phở 24 Nguyễn Hữu Thọ',
    category: 'Phở & Bún', cuisine: 'Việt Nam',
    address: '120 Nguyễn Hữu Thọ, P. Tân Hưng',
    ward: 'Tân Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['phở', 'chuỗi', 'việt nam'],
    description: 'Phở 24 chuẩn vị với nước dùng thanh, phù hợp mọi lứa tuổi.',
    open_hours: '07:00–22:00',
  },
  {
    name: 'Nướng Hải Sản Hải Phòng Q7',
    category: 'Hải sản', cuisine: 'Việt Nam',
    address: '88 Nguyễn Hữu Thọ, P. Tân Hưng',
    ward: 'Tân Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['hải sản', 'nướng', 'tôm hùm', 'nhóm'],
    description: 'Hải sản tươi sống: tôm, mực, ốc hấp và nướng than hoa.',
    open_hours: '10:00–23:00',
  },
  {
    name: 'Bò Né Phú Mỹ',
    category: 'Bò né & Sáng', cuisine: 'Việt Nam',
    address: '204 Nguyễn Hữu Thọ, P. Tân Hưng',
    ward: 'Tân Hưng',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$', tags: ['bò né', 'sáng', 'bít tết', 'việt nam'],
    description: 'Bò né chảo nóng với bít tết, pa tê, bánh mì và trứng ốp la.',
    open_hours: '06:00–12:00',
  },
  {
    name: 'Cơm Tấm 36 Nguyễn Hữu Thọ',
    category: 'Cơm tấm', cuisine: 'Việt Nam',
    address: '36 Nguyễn Hữu Thọ, P. Tân Hưng',
    ward: 'Tân Hưng',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['cơm tấm', 'sườn', 'việt nam', 'bình dân'],
    description: 'Cơm tấm sườn nướng đặc biệt, nước mắm chua ngọt đậm vị.',
    open_hours: '06:30–21:30',
  },

  // ── HUỲNH TẤN PHÁT / TÂN THUẬN ───────────────────────────────────────────
  {
    name: 'Hủ Tiếu Nam Vang Tân Thuận',
    category: 'Hủ tiếu & Mì', cuisine: 'Việt Nam',
    address: '68 Huỳnh Tấn Phát, P. Tân Thuận Tây',
    ward: 'Tân Thuận Tây',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$', tags: ['hủ tiếu', 'nam vang', 'việt nam'],
    description: 'Hủ tiếu Nam Vang khô và nước với tôm, thịt băm, trứng cút.',
    open_hours: '06:00–14:00',
  },
  {
    name: 'Bún Riêu Cua Bà Thảo',
    category: 'Phở & Bún', cuisine: 'Việt Nam',
    address: '42 Huỳnh Tấn Phát, P. Tân Thuận Tây',
    ward: 'Tân Thuận Tây',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['bún riêu', 'cua', 'việt nam'],
    description: 'Bún riêu cua đồng nguyên chất, cà chua tươi và đậu phụ.',
    open_hours: '06:30–13:00',
  },
  {
    name: 'Mì Quảng Đà Nẵng Q7',
    category: 'Phở & Bún', cuisine: 'Việt Nam',
    address: '15 Lý Phục Man, P. Bình Thuận',
    ward: 'Bình Thuận',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$', tags: ['mì quảng', 'đà nẵng', 'tôm thịt', 'việt nam'],
    description: 'Mì Quảng tôm thịt chuẩn vị Đà Nẵng, nước nhân đậm đà.',
    open_hours: '07:00–20:00',
  },
  {
    name: 'Lẩu Thái Mama Q7',
    category: 'Lẩu & Nướng', cuisine: 'Thái Lan',
    address: '78 Đào Trí, P. Phú Thuận',
    ward: 'Phú Thuận',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['lẩu thái', 'chua cay', 'hải sản', 'nhóm'],
    description: 'Lẩu Thái chua cay đặc trưng với hải sản tươi và rau cuốn.',
    open_hours: '10:00–23:00',
  },

  // ── ĐỒ HÀN / NHẬT / KHÁC ──────────────────────────────────────────────────
  {
    name: 'Samgyeopsal 88 Q7',
    category: 'Nướng Hàn Quốc', cuisine: 'Hàn Quốc',
    address: '88 Nguyễn Thị Thập, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['nướng hàn', 'ba chỉ', 'soju', 'nhóm', 'hàn quốc'],
    description: 'Nướng ba chỉ Hàn không khói, banchan đa dạng, có soju.',
    open_hours: '11:00–23:00',
  },
  {
    name: 'GoGi House Phú Mỹ Hưng',
    category: 'Nướng Hàn Quốc', cuisine: 'Hàn Quốc',
    address: '72 Nguyễn Đức Cảnh, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['nướng hàn', 'buffet', 'ba chỉ', 'hàn quốc'],
    description: 'Buffet nướng Hàn GoGi House, đa dạng thịt và banchan.',
    open_hours: '10:00–22:30',
  },
  {
    name: 'Sushi Hokkaido Sachi Q7',
    category: 'Sushi & Nhật Bản', cuisine: 'Nhật Bản',
    address: '48A Nguyễn Thị Thập, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$$', tags: ['sushi', 'sashimi', 'nhật bản', 'hokkaido'],
    description: 'Sushi Hokkaido chuẩn vị Nhật, cá hồi tươi và omakase mini.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'Ichiba Q7',
    category: 'Ramen & Nhật Bản', cuisine: 'Nhật Bản',
    address: '6 Hoàng Văn Thái, P. Tân Phú',
    ward: 'Tân Phú',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['ramen', 'udon', 'nhật bản', 'gyudon'],
    description: 'Ramen tonkotsu và udon nóng hổi, cơm bò gyudon Nhật.',
    open_hours: '10:00–21:30',
  },
  {
    name: 'Tiệm Bún Chả Hà Nội Q7',
    category: 'Bún chả & Miền Bắc', cuisine: 'Việt Nam',
    address: '33 Lê Văn Thiêm, P. Phú Mỹ',
    ward: 'Phú Mỹ',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$', tags: ['bún chả', 'hà nội', 'miền bắc', 'việt nam'],
    description: 'Bún chả Hà Nội chả nướng than, nước chấm chua ngọt chuẩn bắc.',
    open_hours: '10:00–20:00',
  },
  {
    name: 'Gà Rán Uncle Bills Q7',
    category: 'Gà rán', cuisine: 'Việt Nam',
    address: '102 Nguyễn Hữu Thọ, P. Tân Hưng',
    ward: 'Tân Hưng',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['gà rán', 'burger', 'bình dân', 'việt nam'],
    description: 'Gà rán giòn rụm kiểu Việt, burger và cơm gà giá bình dân.',
    open_hours: '09:00–22:00',
  },
  {
    name: 'Bánh Cuốn Thanh Trì Q7',
    category: 'Bánh cuốn & Sáng', cuisine: 'Việt Nam',
    address: '19 Trần Xuân Soạn, P. Tân Kiểng',
    ward: 'Tân Kiểng',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$', tags: ['bánh cuốn', 'miền bắc', 'sáng', 'việt nam'],
    description: 'Bánh cuốn Thanh Trì mỏng mịn, nhân thịt nấm, chả lụa.',
    open_hours: '06:00–11:30',
  },
  {
    name: 'Quán Ăn Ngon Phú Mỹ Hưng',
    category: 'Ẩm thực Việt đa dạng', cuisine: 'Việt Nam',
    address: '14 Phố Nhà Hàng, Phú Mỹ Hưng, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['đa dạng', 'việt nam', 'phố nhà hàng', 'nhóm'],
    description: 'Khu phố nhà hàng Phú Mỹ Hưng với nhiều món Việt truyền thống.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'Cheese Coffee Phú Mỹ Hưng',
    category: 'Cà phê', cuisine: 'Việt Nam',
    address: '10 Nguyễn Đức Cảnh, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['cà phê', 'cheese cream', 'trà', 'việt nam'],
    description: 'Cà phê phủ kem phô mai béo ngậy, trà đào cam sả và ép trái cây.',
    open_hours: '07:00–22:00',
  },
  {
    name: 'Ăn Vặt Đà Lạt Q7',
    category: 'Ăn vặt & Tráng miệng', cuisine: 'Việt Nam',
    address: '65 Trần Xuân Soạn, P. Tân Kiểng',
    ward: 'Tân Kiểng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['ăn vặt', 'đà lạt', 'bánh tráng', 'xúc xích'],
    description: 'Bánh tráng nướng Đà Lạt, xúc xích chiên, sữa chua trân châu.',
    open_hours: '14:00–22:00',
  },
  {
    name: 'Trà Vinh TP.HCM Q7',
    category: 'Trà & Đồ uống', cuisine: 'Việt Nam',
    address: '33 Nguyễn Thị Thập, P. Tân Phú',
    ward: 'Tân Phú',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['trà sữa', 'việt nam', 'hải sản'],
    description: 'Trà sữa Trà Vinh với trân châu nóng, thạch dừa và sữa dừa.',
    open_hours: '09:00–23:00',
  },
  {
    name: 'Pizza 4Ps Phú Mỹ Hưng',
    category: 'Pizza & Mì Ý', cuisine: 'Nhật-Ý',
    address: 'Shophouse 6, khu Phú Mỹ Hưng, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$$$', tags: ['pizza', 'phô mai', 'nhật ý', 'cao cấp', 'phú mỹ hưng'],
    description: 'Pizza 4Ps nổi tiếng phô mai tự làm, pizza lò củi và half-half.',
    open_hours: '11:00–22:00',
  },
  {
    name: 'Pho Street Q7',
    category: 'Phở & Bún', cuisine: 'Việt Nam',
    address: '24 Nguyễn Văn Linh, P. Tân Phong',
    ward: 'Tân Phong',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['phở', 'bún bò', 'việt nam', 'nước dùng'],
    description: 'Phở bò tái, phở gà với xương hầm 8 tiếng, ăn sáng và trưa.',
    open_hours: '06:00–14:00',
  },
  {
    name: 'Mì Tôm Hải Sản Bờ Biển',
    category: 'Mì & Hải sản', cuisine: 'Việt Nam',
    address: '44 Đào Trí, P. Phú Thuận',
    ward: 'Phú Thuận',
    platforms: { grab: true, shopee_food: false, be_food: false },
    price_range: '$$', tags: ['hải sản', 'mì tôm', 'tôm', 'mực', 'việt nam'],
    description: 'Tô mì tôm hải sản siêu to, đầy tôm sú, mực và cá viên.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'The Alley Q7',
    category: 'Trà & Đồ uống', cuisine: 'Đài Loan',
    address: '80 Nguyễn Thị Thập, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['trà sữa', 'đài loan', 'hươu', 'trân châu'],
    description: 'The Alley trà sữa cao cấp Đài Loan, hươu vàng icon, topping đặc biệt.',
    open_hours: '09:30–22:00',
  },
  {
    name: 'Yi Fang Taiwan Fruit Tea Q7',
    category: 'Trà & Đồ uống', cuisine: 'Đài Loan',
    address: '12 Lê Văn Lương, P. Tân Hưng',
    ward: 'Tân Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['trà hoa quả', 'đài loan', 'chanh dây', 'thơm'],
    description: 'Yi Fang trà trái cây tươi Đài Loan, chanh dây và thơm đặc trưng.',
    open_hours: '09:00–22:00',
  },
  {
    name: 'Cơm Gà Xối Mỡ Ba Ghiền',
    category: 'Cơm gà', cuisine: 'Việt Nam',
    address: '57 Bùi Văn Ba, P. Tân Thuận Đông',
    ward: 'Tân Thuận Đông',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['cơm gà', 'xối mỡ', 'sài gòn', 'việt nam'],
    description: 'Cơm gà xối mỡ giòn da vàng ruộm, nước mắm gừng đặc biệt.',
    open_hours: '10:00–21:30',
  },
  {
    name: 'Lẩu Bò Mỹ Thiện Q7',
    category: 'Lẩu & Nướng', cuisine: 'Việt Nam',
    address: '130 Lê Văn Lương, P. Tân Hưng',
    ward: 'Tân Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$$', tags: ['lẩu bò', 'nhúng dấm', 'nhóm', 'việt nam'],
    description: 'Lẩu bò nhúng dấm và cuộn lá lốt, nước lẩu chua ngọt chuẩn Nam.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'Trà Sữa BOBAPOP Q7',
    category: 'Trà & Đồ uống', cuisine: 'Việt Nam',
    address: '39 Nguyễn Hữu Thọ, P. Tân Hưng',
    ward: 'Tân Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['trà sữa', 'boba', 'màu sắc', 'việt nam'],
    description: 'Trà sữa boba màu sắc đa dạng, giá bình dân phù hợp học sinh sinh viên.',
    open_hours: '08:00–22:30',
  },
  {
    name: 'The Original Boat Noodle',
    category: 'Mì Thái', cuisine: 'Thái Lan',
    address: '48 Nguyễn Thị Thập, P. Tân Phú',
    ward: 'Tân Phú', area: 'Phú Mỹ Hưng',
    platforms: { grab: true, shopee_food: true, be_food: false },
    price_range: '$', tags: ['boat noodle', 'mì thái', 'thái lan', 'cay'],
    description: 'Mì thuyền Thái nước đen đặc biệt, ăn nhỏ, order nhiều tô.',
    open_hours: '10:00–22:00',
  },
  {
    name: 'Cơm Văn Phòng Nguyên Sinh Q7',
    category: 'Cơm văn phòng', cuisine: 'Việt Nam',
    address: '203 Nguyễn Văn Linh, P. Tân Phong',
    ward: 'Tân Phong',
    platforms: { grab: true, shopee_food: true, be_food: true },
    price_range: '$', tags: ['cơm bình dân', 'văn phòng', 'giao nhanh', 'việt nam'],
    description: 'Cơm bình dân đa món, giao nhanh trong 30 phút cho văn phòng.',
    open_hours: '06:00–20:30',
  },
];

async function seed() {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/mealcraft';
  await mongoose.connect(uri);
  console.log('✅ MongoDB connected');

  await Restaurant.deleteMany({ district: 'Quận 7' });
  console.log('🗑️  Cleared existing Quận 7 restaurants');

  const inserted = await Restaurant.insertMany(RESTAURANTS);
  console.log(`✅ Seeded ${inserted.length} restaurants in Quận 7`);

  await mongoose.disconnect();
}

seed().catch(err => { console.error(err); process.exit(1); });
